### ISSUE TITLE
4 is not a valid GoogleHomeAlarmStatus

### ISSUE THREAD

**Issue by GuyKh** [leikoilja/ha-google-home#176]
## Describe the bug
Integration fails to load entities. Exceptions in log
![image](https://user-images.githubusercontent.com/3136012/114303277-f7bcf700-9ad5-11eb-9507-05ad6c31c3d8.png)

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.40
```

## Glocaltokens Version (Underlying package)

```text
bash-5.0# pip show glocaltokens
Name: glocaltokens
Version: 0.3.0
```

## Logs

```text
2021-04-11 14:48:40 ERROR (MainThread) [custom_components.google_home] Unexpected error fetching sensor data: 4 is not a valid GoogleHomeAlarmStatus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 246, in update_google_devices_information
    coordinator_data = await asyncio.gather(
  File "/config/custom_components/google_home/api.py", line 220, in collect_data_from_endpoints
    device = await self.get_alarms_and_timers(device, ip_address, auth_token)
  File "/config/custom_components/google_home/api.py", line 139, in get_alarms_and_timers
    device.set_alarms(resp.get(JSON_ALARM))
  File "/config/custom_components/google_home/models.py", line 46, in set_alarms
    self._alarms = [
  File "/config/custom_components/google_home/models.py", line 47, in <listcomp>
    GoogleHomeAlarm(
  File "/config/custom_components/google_home/models.py", line 144, in __init__
    self.status = GoogleHomeAlarmStatus(status)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 4 is not a valid GoogleHomeAlarmStatus```

## Debug log

<!-- To enable debug logs, put the below snippet in your configuration.yaml file.
You can delete the below snippet before you submit this issue.
-->

```yaml
logger:
  default: debug
  logs:
    custom_components.google_home: debug
```

```text

2021-04-11 14:52:42 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Living Room TV - https://192.168.1.AAA:8443/setup/assistant/alarms
2021-04-11 14:52:42 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Entryway clock - https://192.168.1.AAA:8443/setup/assistant/alarms
2021-04-11 14:52:42 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Bedroom speaker - https://192.168.1.AAA:8443/setup/assistant/alarms
2021-04-11 14:52:42 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Kitchen speaker - https://192.168.1.AAA:8443/setup/assistant/alarms
2021-04-11 14:52:43 ERROR (MainThread) [custom_components.google_home] Unexpected error fetching sensor data: 4 is not a valid GoogleHomeAlarmStatus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 246, in update_google_devices_information
    coordinator_data = await asyncio.gather(
  File "/config/custom_components/google_home/api.py", line 220, in collect_data_from_endpoints
    device = await self.get_alarms_and_timers(device, ip_address, auth_token)
  File "/config/custom_components/google_home/api.py", line 139, in get_alarms_and_timers
    device.set_alarms(resp.get(JSON_ALARM))
  File "/config/custom_components/google_home/models.py", line 46, in set_alarms
    self._alarms = [
  File "/config/custom_components/google_home/models.py", line 47, in <listcomp>
    GoogleHomeAlarm(
  File "/config/custom_components/google_home/models.py", line 144, in __init__
    self.status = GoogleHomeAlarmStatus(status)
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: 4 is not a valid GoogleHomeAlarmStatus
2021-04-11 14:52:43 DEBUG (MainThread) [custom_components.google_home] Finished fetching sensor data in 23.034 seconds

```

**Comment by KapJI** [comment]
Do you know what `4` means?

```python
class GoogleHomeAlarmStatus(Enum):
    """Definition of Google Home alarm status"""

    NONE = 0
    SET = 1
    RINGING = 2
    SNOOZED = 3
```

**Comment by KapJI** [comment]
@AstroViking any ideas?

**Comment by GuyKh** [comment]
When I check which alarms are there the Google Home Mini

There are these two (Music Alarms in Spotify)
![Screenshot_20210411-231945_Home](https://user-images.githubusercontent.com/3136012/114319986-7d639580-9b1c-11eb-8038-1220b99aa68b.jpg)

**Comment by KapJI** [comment]
How did you set it? I tried various media alarms including recurring ones but they always just have "set" state.

**Comment by GuyKh** [comment]
> How did you set it? I tried various media alarms including recurring ones but they always just have "set" state.

'''
- OK Google, Set a music alarm at 8am
- Sure. And what would music would like to play? 
- The beatles
- Sure, The Beatles at 8am. Set.
'''

Or something simiar

**Comment by KapJI** [comment]
Yeah, I did exactly that. In my case it gets "set" state. I even checked that while playing it has "ringing" state and after cancelled it has "set" again for the next day. We can probably mark 4 as unknown but it's interesting to figure out what it really means.

**Comment by GuyKh** [comment]
Perhaps it's due to the alarm being set only Sun-Thu maybe?

**Comment by leikoilja** [comment]
@GuyKh, the fix if merge #181, we'll release it in a few days to test :)

**Comment by AstroViking** [comment]
> @AstroViking any ideas?

Actually no clue either... Never seen that state before. 🤔

**Comment by leikoilja** [comment]
@GuyKh, please give it a try and let us know: https://github.com/leikoilja/ha-google-home/releases/tag/v1.4.1

**Comment by whitehead-aa** [comment]
On Lenovo smart clock "state_four" comes back when I make the alarm inactive:
![image](https://user-images.githubusercontent.com/31188516/114435435-0d0c5100-9bbc-11eb-95d7-4ac8ed2e7b40.png)
![image](https://user-images.githubusercontent.com/31188516/114435950-b18e9300-9bbc-11eb-8e6c-779bd1a7ef05.png)

When setting it active again status changes to set:
![image](https://user-images.githubusercontent.com/31188516/114435525-28775c00-9bbc-11eb-9633-96be1983b007.png)
![image](https://user-images.githubusercontent.com/31188516/114435905-a63b6780-9bbc-11eb-8491-1d96f81a414e.png)

I will try on a home hub as well but currently is not responding.

**Comment by KapJI** [comment]
I tried on Nest Hub Mini but it also doesn't respond (even to Google Home app).

**Comment by KapJI** [comment]
@whitehead-aa can you try to pause timer on lenovo clock? Maybe we have missing status there as well?

**Comment by whitehead-aa** [comment]
Status returns 2 when the timer is paused (tried with both voice and touchscreen)

However HA shows all sensors for the device as "unavailable" while the timer is paused. I will get some logs and raise that as a separate issue

**Comment by KapJI** [comment]
Here is the fix: https://github.com/leikoilja/ha-google-home/pull/185

**Comment by KapJI** [comment]
@whitehead-aa it's merged. Can you test the master?

**Comment by whitehead-aa** [comment]
Alarm looks ok.

![image](https://user-images.githubusercontent.com/31188516/114453141-266bc800-9bd1-11eb-9f86-40c526f686de.png)

There are other problems with pausing the timer so I Can't check that

**Comment by wifiuk** [comment]
![image](https://user-images.githubusercontent.com/3785545/145732827-6f04bf6e-e2c0-419c-8ef5-60b5f09849f1.png)
im getting this, tried removed and reinstall of the custom plugin, but no idea how to fix


**Log Error Info**
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 139, in update_google_devices_information
    coordinator_data = await asyncio.gather(
  File "/config/custom_components/google_home/api.py", line 152, in collect_data_from_endpoints
    device = await self.update_alarms_and_timers(device)
  File "/config/custom_components/google_home/api.py", line 168, in update_alarms_and_timers
    device.set_alarms(cast(List[AlarmJsonDict], response[JSON_ALARM]))
  File "/config/custom_components/google_home/models.py", line 48, in set_alarms
    self._alarms = [
  File "/config/custom_components/google_home/models.py", line 49, in <listcomp>
    GoogleHomeAlarm(
  File "/config/custom_components/google_home/models.py", line 169, in __init__
    self.status = GoogleHomeAlarmStatus(status)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 5 is not a valid GoogleHomeAlarmStatus

`


![image](https://user-images.githubusercontent.com/3785545/145732920-ef34e425-0151-4041-8969-6346c8544644.png)

**Comment by KapJI** [comment]
Please open a separate issue for that.

These are alarm statuses which we know: https://github.com/leikoilja/ha-google-home/blob/master/custom_components/google_home/models.py#L190-L197
How do you get 5?
