### ISSUE TITLE
Pausing a timer causes all sensors to go to "unavailable" 

### ISSUE THREAD

**Issue by whitehead-aa** [leikoilja/ha-google-home#187]
## Describe the bug
Pausing a timer causes all sensors, that are part of this integration, to go to "unavailable" 
Once the timer is un-paused all sensors start to work again
![image](https://user-images.githubusercontent.com/31188516/114455718-f5d95d80-9bd3-11eb-8343-bfdaecce1057.png)

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
v1.4.1
master (46bcfc1)

```

## Logs

```text
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Living room speaker - https://192.168.8.205:8443/setup/assistant/alarms
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device SHIELD - https://192.168.8.243:8443/setup/assistant/alarms
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Office clock - https://192.168.8.9:8443/setup/assistant/alarms
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Kitchen home - https://192.168.8.6:8443/setup/assistant/alarms
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Fetching data from Google Home device Living Room display - https://192.168.8.123:8443/setup/assistant/alarms
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Failed to fetch data from Living room speaker, API returned 404. The device(hardware='Chromecast Audio') is possibly not Google Home compatible and has no alarms/timers. Will retry later.
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Getting Do Not Disturb setting from Google Home device Living room speaker
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Requesting endpoint setup/assistant/notifications for Google Home device Living room speaker - https://192.168.8.205:8443/setup/assistant/notifications
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Failed to fetch data from SHIELD, API returned 404. The device(hardware='SHIELD Android TV') is possibly not Google Home compatible and has no alarms/timers. Will retry later.
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Getting Do Not Disturb setting from Google Home device SHIELD
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Requesting endpoint setup/assistant/notifications for Google Home device SHIELD - https://192.168.8.243:8443/setup/assistant/notifications
2021-04-12 20:56:41 ERROR (MainThread) [custom_components.google_home] Unexpected error fetching sensor data: 'fire_time'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
return await self.update_method()
File "/config/custom_components/google_home/api.py", line 246, in update_google_devices_information
coordinator_data = await asyncio.gather(
File "/config/custom_components/google_home/api.py", line 220, in collect_data_from_endpoints
device = await self.get_alarms_and_timers(device, ip_address, auth_token)
File "/config/custom_components/google_home/api.py", line 138, in get_alarms_and_timers
device.set_timers(resp.get(JSON_TIMER))
File "/config/custom_components/google_home/models.py", line 59, in set_timers
self._timers = [
File "/config/custom_components/google_home/models.py", line 62, in <listcomp>
fire_time=timer["fire_time"],
KeyError: 'fire_time'
2021-04-12 20:56:41 DEBUG (MainThread) [custom_components.google_home] Finished fetching sensor data in 0.038 seconds
2021-04-12 20:56:41 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.bedroom_clock_device, old_state=<state sensor.bedroom_clock_device=TOKEN; device_name=Bedroom clock, auth_token=TOKEN, ip_address=192.168.8.8, hardware=Lenovo Smart Clock, available=True, integration=google_home, friendly_name=Bedroom clock device, icon=mdi:form-textbox-password @ 2021-04-12T20:50:27.473474+01:00>, new_state=<state sensor.bedroom_clock_device=unavailable; friendly_name=Bedroom clock device, icon=mdi:form-textbox-password @ 2021-04-12T20:56:41.044334+01:00>>
2021-04-12 20:56:41 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.bedroom_clock_alarms, old_state=<state sensor.bedroom_clock_alarms=2021-04-13T06:30:00+01:00; next_alarm_status=inactive, alarms=[{'alarm_id': 'alarm/470f9193-9d44-43b6-bda6-63ee8586bd35', 'fire_time': 1618291800, 'status': 'inactive', 'label': None, 'recurrence': None}, {'alarm_id': 'alarm/b20f9db8-0b46-4d0a-9633-dbbf551c243d', 'fire_time': 1618296000, 'status': 'set', 'label': None, 'recurrence': [1, 2, 3, 4, 5]}], integration=google_home, friendly_name=Bedroom clock alarms, icon=mdi:alarm-multiple, device_class=timestamp @ 2021-04-12T20:50:27.475323+01:00>, new_state=<state sensor.bedroom_clock_alarms=unavailable; friendly_name=Bedroom clock alarms, icon=mdi:alarm-multiple, device_class=timestamp @ 2021-04-12T20:56:41.045833+01:00>>
```

**Comment by whitehead-aa** [comment]
Suspect this is caused because there is no "fire_time" attribute when the timer is paused

When Paused:
```text
{"alarm":[{"date_pattern":{"day":13,"month":4,"year":2021},"fire_time":1.6182918e+12,"id":"alarm/470f9193-9d44-43b6-bda6-63ee8586bd35","status":4,"time_pattern":{"hour":6,"minute":30,"second":0}},{"fire_time":1.618296e+12,"id":"alarm/b20f9db8-0b46-4d0a-9633-dbbf551c243d","recurrence":[1,2,3,4,5],"status":1,"time_pattern":{"hour":7,"minute":40,"second":0}}],"timer":[{"id":"timer/f34ab61a-98cc-e4e7-37bc-a3b28b70a5ec","original_duration":60000.0,"remaining_duration":53409.0,"status":2}]}
```
When timer running:
```text
{"alarm":[{"date_pattern":{"day":13,"month":4,"year":2021},"fire_time":1.6182918e+12,"id":"alarm/470f9193-9d44-43b6-bda6-63ee8586bd35","status":4,"time_pattern":{"hour":6,"minute":30,"second":0}},{"fire_time":1.618296e+12,"id":"alarm/b20f9db8-0b46-4d0a-9633-dbbf551c243d","recurrence":[1,2,3,4,5],"status":1,"time_pattern":{"hour":7,"minute":40,"second":0}}],"timer":[{"fire_time":1.618258941e+12,"id":"timer/f34ab61a-98cc-e4e7-37bc-a3b28b70a5ec","original_duration":60000.0,"status":1}]}

```

**Comment by KapJI** [comment]
That's right, I'll fix it.

**Comment by leikoilja** [comment]
Let's get that release going 🔥

**Comment by KapJI** [comment]
@whitehead-aa please try 1.4.2.

**Comment by whitehead-aa** [comment]
When paused "Next timer Status" reports paused.  on UI
![image](https://user-images.githubusercontent.com/31188516/114589159-51acf080-9c7f-11eb-97f3-65b77e5b809f.png)

Other sensors remain working. 

tested on v1.4.2

Note: The State when timer paused is still "unavailable"  but I think that's intentional.
