### ISSUE TITLE
Integration does not load in 2021.12: Unable to import component: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const'

### ISSUE THREAD

**Issue by eIiot** [leikoilja/ha-google-home#410]
## Describe the bug

Integration fails to load in 2021.12 B1.

Steps to reproduce:
- Install 2021.12
- Restart

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
v1.9.1
```

## Logs

```text
2021-12-03 18:25:38 WARNING (SyncWorker_9) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-12-03 18:25:40 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'tplink', 'notify', 'automation', 'group', 'alarmo', 'wyzeapi', 'hpprinter', 'logbook', 'persistent_notification', 'climate', 'tile', 'esphome', 'tts', 'tuya', 'dhcp', 'counter', 'ffmpeg', 'minecraft_server', 'network', 'browser_mod', 'simpleicons', 'timer', 'scene', 'trace', 'stream', 'ifttt', 'govee', 'input_select', 'mail_and_packages', 'mobile_app', 'ios', 'camera', 'rest_command', 'google_home', 'input_text', 'my', 'sun', 'hacs', 'zoom', 'panel_custom', 'input_datetime', 'zone', 'spotify', 'roku', 'input_boolean', 'light', 'meross_lan', 'speedtestdotnet', 'updater', 'switch', 'mqtt', 'tag', 'discovery', 'blueprint', 'input_number', 'sleep_as_android', 'device_tracker', 'system_health', 'shell_command', 'history', 'binary_sensor', 'cast', 'script', 'zeroconf', 'sensor', 'zha'}
2021-12-03 18:25:44 ERROR (MainThread) [homeassistant.setup] Setup failed for google_home: Unable to import component: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2021-12-03 18:25:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2021-12-03 18:25:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
File "/config/custom_components/google_home/__init__.py", line 17, in <module>
from .api import GlocaltokensApiClient
File "/config/custom_components/google_home/api.py", line 14, in <module>
from homeassistant.const import HTTP_NOT_FOUND, HTTP_OK, HTTP_UNAUTHORIZED
ImportError: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 74, in _async_process_pending_flows
await gather_with_concurrency(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 170, in gather_with_concurrency
return await gather(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in sem_task
return await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 725, in async_create_flow
raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2021-12-03 18:25:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2021-12-03 18:25:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2021-12-03 18:25:56 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2021-12-03 18:25:56 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_home: cannot import name 'HTTP_NOT_FOUND' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by kaosmagix** [comment]
I have the same issue after upgrading to core-2021.12.0b0

**Comment by rootiest** [comment]
Breaking change here:

https://github.com/home-assistant/core/pull/58380

**Comment by KapJI** [comment]
That was already fixed in https://github.com/leikoilja/ha-google-home/pull/374. We just need to release the new version.

**Comment by KapJI** [comment]
1.9.2 is released.
