### ISSUE TITLE
5 is not a valid GoogleHomeAlarmStatus

### ISSUE THREAD

**Issue by philippefs35** [leikoilja/ha-google-home#420]
## Describe the bug

Integration fails to load due to an unknown alarm status
![image](https://user-images.githubusercontent.com/1505656/147113937-3abb3962-6bcf-42a6-a289-058ac5a9434c.png)

## Version of the integration

```text
1.9.3
```

## Logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 139, in update_google_devices_information
    coordinator_data = await asyncio.gather(
  File "/config/custom_components/google_home/api.py", line 152, in collect_data_from_endpoints
    device = await self.update_alarms_and_timers(device)
  File "/config/custom_components/google_home/api.py", line 168, in update_alarms_and_timers
    device.set_alarms(cast(List[AlarmJsonDict], response[JSON_ALARM]))
  File "/config/custom_components/google_home/models.py", line 48, in set_alarms
    self._alarms = [
  File "/config/custom_components/google_home/models.py", line 49, in <listcomp>
    GoogleHomeAlarm(
  File "/config/custom_components/google_home/models.py", line 169, in __init__
    self.status = GoogleHomeAlarmStatus(status)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 5 is not a valid GoogleHomeAlarmStatus
```

**Comment by KapJI** [comment]
What alarms do you have set?

How it looks like in the Home app on this screen?
![image](https://user-images.githubusercontent.com/3767331/147119536-94fe40e0-f61c-4eab-995d-2707e7ee6942.jpeg)

**Comment by philippefs35** [comment]
So I had the alarm in this screenshot (7:30 Mon, Tue, Wed, Thu, Fri), but it appeared twice:
![image](https://user-images.githubusercontent.com/1505656/147132501-7be715f6-fbfe-4a09-8c95-0b31415e50cc.png)

That is: the exact same line appeared twice (even though it only appeared once on my Nest Hub)

I've now deleted them and recreated the alarm -- everything seems to work

**Comment by KapJI** [comment]
We can add support for that alarm status when we figure out how to create such alarm.

**Comment by greendog99** [comment]
I also have started receiving the `ValueError: 5 is not a valid GoogleHomeAlarmStatus` message every 30 seconds or so, but I'm not using any Google alarms or timers currently. Looks like it's been happening at least for a few days, I don't have any logs older than that.

Let me know if there's any other info I can provide... Thanks!

**Comment by HA-Peet** [comment]
Same here.....

Logger: custom_components.google_home
Source: custom_components/google_home/models.py:169
Integration: Google Home (documentation, issues)
First occurred: 12:16:56 (12 occurrences)
Last logged: 12:36:11

Unexpected error fetching sensor data: 5 is not a valid GoogleHomeAlarmStatus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/google_home/api.py", line 139, in update_google_devices_information
    coordinator_data = await asyncio.gather(
  File "/config/custom_components/google_home/api.py", line 152, in collect_data_from_endpoints
    device = await self.update_alarms_and_timers(device)
  File "/config/custom_components/google_home/api.py", line 168, in update_alarms_and_timers
    device.set_alarms(cast(List[AlarmJsonDict], response[JSON_ALARM]))
  File "/config/custom_components/google_home/models.py", line 48, in set_alarms
    self._alarms = [
  File "/config/custom_components/google_home/models.py", line 49, in <listcomp>
    GoogleHomeAlarm(
  File "/config/custom_components/google_home/models.py", line 169, in __init__
    self.status = GoogleHomeAlarmStatus(status)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 5 is not a valid GoogleHomeAlarmStatus

**Comment by williamg97** [comment]
Also gettiing this issue now. Same error

`2022-01-04 09:40:27 ERROR (MainThread) [custom_components.google_home] Unexpected error fetching sensor data: 5 is not a valid GoogleHomeAlarmStatus
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/google_home/api.py", line 139, in update_google_devices_information
coordinator_data = await asyncio.gather(
File "/config/custom_components/google_home/api.py", line 152, in collect_data_from_endpoints
device = await self.update_alarms_and_timers(device)
File "/config/custom_components/google_home/api.py", line 168, in update_alarms_and_timers
device.set_alarms(cast(List[AlarmJsonDict], response[JSON_ALARM]))
File "/config/custom_components/google_home/models.py", line 48, in set_alarms
self._alarms = [
File "/config/custom_components/google_home/models.py", line 49, in <listcomp>
GoogleHomeAlarm(
File "/config/custom_components/google_home/models.py", line 169, in __init__
self.status = GoogleHomeAlarmStatus(status)
File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
raise ve_exc
ValueError: 5 is not a valid GoogleHomeAlarmStatus`

**Comment by williamg97** [comment]
Looks like its a new "missed" status. Similar to issue #176. Have created a PR that should fix it! 

![image](https://user-images.githubusercontent.com/12609619/148130558-45ef01b1-42c8-4bbf-939d-08a9e646be49.png)

**Comment by leikoilja** [comment]
Big kuddos to @williamg97 for fixing the issue with `missed alarm` status 5. 
Please upgrade the integration to version v1.9.4 using Hacs in HA.
https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.4
If you still encounter any issues please open new issue ticket :)
