### ISSUE TITLE
Version 1.9.6 fails to install glocaltokens==0.6.1 in home assistant official containers

### ISSUE THREAD

**Issue by skgsergio** [leikoilja/ha-google-home#453]
## Describe the bug

With the last release (v1.9.6) the integration is unable to start due to dependency install failure due to missing c++ in the container.

This is probably related to a dependency not having a wheel for the Python/OS version of the official Home Assistant containers.

## Version of the integration

```text
1.9.6
```

## Logs

```text
Unable to install package glocaltokens==0.6.1: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mqsqsqz6/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mqsqsqz6/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rczzd0sb cwd: /tmp/pip-install-mqsqsqz6/grpcio-tools/ Complete output (11 lines): Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-mqsqsqz6/grpcio-tools/setup.py", line 180, in <module> if check_linker_need_libatomic(): File "/tmp/pip-install-mqsqsqz6/grpcio-tools/setup.py", line 91, in check_linker_need_libatomic cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'], File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'c++' ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 22.0.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by craigmate** [comment]
I also got this error when I upgraded to v1.9.6

**Comment by JeffersonBledsoe** [comment]
Just came here to say I'm getting the same error. I'm on 2022.02.1:

`Setup failed for google_home: Requirements for google_home not found: ['glocaltokens==0.6.1'].`

**Comment by KapJI** [comment]
On my system it's being installed from wheels as expected:
```
❯ pip install --force-reinstall grpcio-tools==1.43.0
Collecting grpcio-tools==1.43.0
  Using cached grpcio_tools-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Collecting protobuf<4.0dev,>=3.5.0.post1
  Using cached protobuf-3.19.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting setuptools
  Using cached setuptools-60.7.1-py3-none-any.whl (1.0 MB)
Collecting grpcio>=1.43.0
  Using cached grpcio-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: protobuf, setuptools, six, grpcio, grpcio-tools
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.4
    Uninstalling protobuf-3.19.4:
      Successfully uninstalled protobuf-3.19.4
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.7.1
    Uninstalling setuptools-60.7.1:
      Successfully uninstalled setuptools-60.7.1
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.43.0
    Uninstalling grpcio-1.43.0:
      Successfully uninstalled grpcio-1.43.0
  Attempting uninstall: grpcio-tools
    Found existing installation: grpcio-tools 1.43.0
    Uninstalling grpcio-tools-1.43.0:
      Successfully uninstalled grpcio-tools-1.43.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

glocaltokens 0.6.1 requires zeroconf<0.37.0,>=0.36.2, but you'll have zeroconf 0.38.3 which is incompatible.
audio-metadata 0.11.1 requires attrs<19.4,>=18.2, but you'll have attrs 21.2.0 which is incompatible.
Successfully installed grpcio-1.43.0 grpcio-tools-1.43.0 protobuf-3.19.4 setuptools-60.7.1 six-1.16.0
```

@allenporter can you help us here? Why grpcio is not installed from wheels on the official HA container?

**Comment by KapJI** [comment]
On my system it's being installed from wheels as expected:
```
❯ pip install --force-reinstall grpcio-tools==1.43.0
Collecting grpcio-tools==1.43.0
  Using cached grpcio_tools-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
Collecting protobuf<4.0dev,>=3.5.0.post1
  Using cached protobuf-3.19.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Collecting setuptools
  Using cached setuptools-60.7.1-py3-none-any.whl (1.0 MB)
Collecting grpcio>=1.43.0
  Using cached grpcio-1.43.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
Collecting six>=1.5.2
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: protobuf, setuptools, six, grpcio, grpcio-tools
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.4
    Uninstalling protobuf-3.19.4:
      Successfully uninstalled protobuf-3.19.4
  Attempting uninstall: setuptools
    Found existing installation: setuptools 60.7.1
    Uninstalling setuptools-60.7.1:
      Successfully uninstalled setuptools-60.7.1
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.43.0
    Uninstalling grpcio-1.43.0:
      Successfully uninstalled grpcio-1.43.0
  Attempting uninstall: grpcio-tools
    Found existing installation: grpcio-tools 1.43.0
    Uninstalling grpcio-tools-1.43.0:
      Successfully uninstalled grpcio-tools-1.43.0
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

glocaltokens 0.6.1 requires zeroconf<0.37.0,>=0.36.2, but you'll have zeroconf 0.38.3 which is incompatible.
audio-metadata 0.11.1 requires attrs<19.4,>=18.2, but you'll have attrs 21.2.0 which is incompatible.
Successfully installed grpcio-1.43.0 grpcio-tools-1.43.0 protobuf-3.19.4 setuptools-60.7.1 six-1.16.0
```

@allenporter can you help us here? Why grpcio is not installed from wheels on the official HA container?

@skgsergio @craigmate @JeffersonBledsoe can you try to install it manually from HA venv?

**Comment by TheFes** [comment]
Got the same error, thought I might be able to fix it by removing the integration and adding it again, but the I get:
![image](https://user-images.githubusercontent.com/28803438/152510790-c2586ec0-1a45-4b66-bfcd-b133025cbcc7.png)

**Comment by KapJI** [comment]
As a short term solution you should be able to install the compiler (c++) inside the container. It should be something like but may depend on your platform:
```shell
apk install gcc
```

**Comment by skgsergio** [comment]
Home Assistant containers are:
- OS: `Alpine Linux 3.14`
- Python: `Python 3.9.7`

I can see the container has installed `grpcio-tools==1.31.0`. Probably wheels doesn't work due to Alpine Linux using musl.

I don't find manually installing `gcc` is a solution since these containers are shipped officially by Home Assistant and updates (and other actions) will recreate the container.

I've downgraded this component until there is a decision over this.

Trying to manually install `grpcio-tools==1.43.0`:
``` 
bash-5.1# pip3 install grpcio-tools==1.43.0
Collecting grpcio-tools==1.43.0
  Using cached grpcio-tools-1.43.0.tar.gz (2.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-erx9lsbe/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-erx9lsbe/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tv3325nl
         cwd: /tmp/pip-install-erx9lsbe/grpcio-tools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-erx9lsbe/grpcio-tools/setup.py", line 180, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-erx9lsbe/grpcio-tools/setup.py", line 91, in check_linker_need_libatomic
        cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by KapJI** [comment]
@skgsergio I think it should use this: https://github.com/allenporter/wheels-grpc/

**Comment by skgsergio** [comment]
Yep, they use that wheels repo for wheels that work in alpine, and indeed this version is not there, looks like they internally use `1.31.0`:

https://wheels.home-assistant.io/alpine-3.14/amd64/

[grpcio_tools-1.31.0-cp39-none-any.whl](https://wheels.home-assistant.io/alpine-3.14/amd64/grpcio_tools-1.31.0-cp39-none-any.whl)              23-Aug-2021 21:53             2380097

So I think that upgrading a dependency they internally use might not be a good idea :/

**Comment by KapJI** [comment]
It's there for armv7 and aarch64. Amd64 should fallback to public wheels. Maybe that fallback mechanism doesn't work.

**Comment by skgsergio** [comment]
`grpcio==1.43` is a different thing from `grpcio-tools==1.43.0`, in fact the first one is installed in the official container:

```
$ docker exec -it homeassistant pip freeze | grep grpcio
grpcio==1.43.0
grpcio-status==1.43.0
grpcio-tools==1.31.0
```

> It's there for armv7 and aarch64. Amd64 should fallback to public wheels. Maybe that fallback mechanism doesn't work.

That is not the issue, the wheels on pypi that link native libraries don't work in Alpine due to the usage of musl instead of glibc. Example using a fresh python 3.9.7 running in alpine 3.14:
```
sconde@ARIEL ~ $ docker run -it --rm docker.io/python:3.9.7-alpine3.14 sh
/ # pip install grpcio-tools==1.43.0
Collecting grpcio-tools==1.43.0
  Downloading grpcio-tools-1.43.0.tar.gz (2.2 MB)
     |████████████████████████████████| 2.2 MB 4.6 MB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fkh0g1c4/grpcio-tools_fe63c472f8ae4e4c8c39650845b86893/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fkh0g1c4/grpcio-tools_fe63c472f8ae4e4c8c39650845b86893/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-oregvszq
         cwd: /tmp/pip-install-fkh0g1c4/grpcio-tools_fe63c472f8ae4e4c8c39650845b86893/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fkh0g1c4/grpcio-tools_fe63c472f8ae4e4c8c39650845b86893/setup.py", line 180, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-fkh0g1c4/grpcio-tools_fe63c472f8ae4e4c8c39650845b86893/setup.py", line 91, in check_linker_need_libatomic
        cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'c++'
    ----------------------------------------
```

**Comment by KapJI** [comment]
So I guess we need wheels for grpcio-tools 1.43 as well?

**Comment by KapJI** [comment]
Ok, I think grpcio-tools is only used for generating protobuf bindings for python. So we can just remove this dependency.
@leikoilja can you check this please?

**Comment by LCMilstein** [comment]
> Got the same error, thought I might be able to fix it by removing the integration and adding it again, but the I get: ![image](https://user-images.githubusercontent.com/28803438/152510790-c2586ec0-1a45-4b66-bfcd-b133025cbcc7.png)

Same for me

**Comment by allenporter** [comment]
My history with these are described here:
https://github.com/home-assistant/core/issues/56669
https://github.com/grpc/grpc/issues/27512

I agree with what was said about about
- yes this is about grpc tools and not grpcio and that difference matters for this wheel
- agree it's trying to compile from source and can't find a compiler, as was said above rather than an musl vs libc link error. So yeah, because it can't find a matching wheel for the specific version and architecture. 
- don't upgrade this dependency from what core is using if you don't need to
- remove the dep if you don't need it at run time (are users machines really compiling protobufs or is this a development component?)
- otherwise come up with a wheel building scheme for all the deps.

**Comment by allenporter** [comment]
By the way we're not using that grpc wheel builder in core. Instead I modified the existing wheel builder in core to builder wheels for grpcio properly.

**Comment by skgsergio** [comment]
Installed component from master and it works again. I did some tests with the sruff I have set up with this component and looks normal.

**Comment by derekpurdy** [comment]
should this be live yet? I am still getting the error.

Thanks

**Comment by joostvkempen** [comment]
works for me! thanks for the great work @KapJI @leikoilja !

**Comment by DanielBaulig** [comment]
Since I updated to HA 2022.3 I am getting "Setup failed for custom integration google_home: Requirements for google_home not found: ['glocaltokens==0.5.2']." on Raspberry Pi 4 with official Docker container. Should I open a new issue or is this the same issue ultimately?
