### ISSUE TITLE
Error when attempting to add integration

### ISSUE THREAD

**Issue by JoelRybacki** [leikoilja/ha-google-home#487]
Running Home Assistant version core-2022.3.5 on Rasperry PI 4.

Downloaded from HACCS.  After HA restart, attempting to add integration, receive the prompt "Config flow could not be loaded: undefined."  Related log errors are below.

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 8:21:51 AM (3 occurrences)
Last logged: 8:22:08 AM

Unable to install package glocaltokens==0.6.2: ERROR: Cannot install glocaltokens==0.6.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

Logger: aiohttp.server
Source: requirements.py:75
First occurred: 8:22:08 AM (1 occurrences)
Last logged: 8:22:08 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 134, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 740, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 75, in async_get_integration_with_requirements
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'google_home' not found.

Logger: homeassistant
Source: requirements.py:180
First occurred: 8:24:35 AM (9 occurrences)
Last logged: 8:24:35 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 740, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 162, in async_process_requirements
    await _async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 180, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for google_home not found: ['glocaltokens==0.6.2'].

**Comment by acbee** [comment]
I'm having a similar issue. Integration was already installed and configured but no longer works. Log reads:

File "/usr/src/homeassistant/homeassistant/requirements.py", line 180, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for google_home not found: ['glocaltokens==0.6.2'].

**Comment by jacobswe** [comment]
Open a pull request [here](https://github.com/leikoilja/ha-google-home/pull/488) that should fix this.

**Comment by leikoilja** [comment]
@acbee, @jacobswe please try updating to 1.9.9, this should be fixed now :) 
https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.9

**Comment by JoelRybacki** [comment]
Confirmed the 1.9.9 HACCS version set up successfully.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ilja Leiko ***@***.***> Date: 3/21/22  9:02 AM  (GMT-05:00) To: leikoilja/ha-google-home ***@***.***> Cc: JoelRybacki ***@***.***>, Author ***@***.***> Subject: Re: [leikoilja/ha-google-home] Error when attempting to add integration (Issue #487) 
@acbee, @jacobswe please try updating to 1.9.9, this should be fixed now :)
https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.9

**Comment by KapJI** [comment]
Btw, the latest is 1.9.15 now.
https://github.com/leikoilja/ha-google-home/releases
