### ISSUE TITLE
Error with latest Beta core 2022.4.0b1

### ISSUE THREAD

**Issue by grantclem** [leikoilja/ha-google-home#503]
## Describe the bug

![image](https://user-images.githubusercontent.com/30598978/161187895-03cd0284-fa1c-400e-9a42-1a55ded604c5.png)

Feedback from Discord suggests the following "That looks like custom components using the string instead of the enum for EntityCategory"

## Version of the integration

[v1.9.9]

```text
Home Assistant 2022.4.0b1
```

## Logs

```text
2022-04-01 10:32:48 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

```

**Comment by grantclem** [comment]
Errors still appearing after b4 install, extra ones this time

```
2022-04-04 18:32:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```
```
2022-04-04 18:32:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```
```
2022-04-04 18:32:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up google_home platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

```

**Comment by leikoilja** [comment]
Big kuddos to @mdegat01 for fixing the EntityCategory enum issue. 💪 🔥 

@grantclem, @mdegat01 please update to the latest 1.9.10 release to verify it has been fixed:
https://github.com/leikoilja/ha-google-home/releases/tag/v1.9.10
