### ISSUE TITLE
Errors still appearing after b4 install, extra ones this time

### ISSUE THREAD

**Issue by grantclem** [leikoilja/ha-google-home#507]
Errors still appearing after b4 install, extra ones this time

```
2022-04-04 18:32:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```
```
2022-04-04 18:32:07 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```
```
2022-04-04 18:32:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up google_home platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

```

_Originally posted by @grantclem in https://github.com/leikoilja/ha-google-home/issues/503#issuecomment-1087422996_

**Comment by mdegat01** [comment]
Are you running the dev version of this component? If you are just running the version of this component you installed from HACS then nothing has changed yet. b4 vs. b3 doesn't matter here, this component needs to ship a new release that includes the fix.

If you want to test the fix in the linked PR you need to follow [the manual install directions](https://github.com/leikoilja/ha-google-home#manual-installation). Then you will be running the dev version and the issue should be fixed there. If you use HACS its still broken.

**Comment by grantclem** [comment]
Hi Mike,

Apologies for the confusion - yes just running the HACS version at this stage. 

Regards

Grant
