### ISSUE TITLE
Integration stopped working, won't set up nor delete

### ISSUE THREAD

**Issue by bmcclure** [leikoilja/ha-google-home#568]
## Describe the bug

This integration was working OK for me, but the other day it started failing completely. I did update to 2022.7 of HA so I'm not sure if that is related or not.

The symptoms are that the integration just says "Setup failed, check your logs" even though it used to work.

In a troubleshooting attempt, I have been trying to simply completely remove the integration and re-set it up from scratch. However, clicking Remove on the integration in the HA UI does nothing, I think that may also be throwing these exceptions.

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.13
```

## Logs

```text
Error occurred loading configuration flow for integration google_home: Exception importing custom_components.google_home.config_flow

Unexpected exception importing platform custom_components.google_home.config_flow
Unexpected exception importing component custom_components.google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 17, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 11, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/client.py", line 24, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 24, in <module>
    _GETASSISTANTROUTINESREQUEST = DESCRIPTOR.message_types_by_name[
KeyError: 'GetAssistantRoutinesRequest'

Setup failed for custom integration google_home: Unable to import component: Exception importing custom_components.google_home
```

I will try and get more debug logs as well.

**Comment by markrgriffin** [comment]
Same issue here 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 17, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 11, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/client.py", line 24, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 24, in <module>
    _GETASSISTANTROUTINESREQUEST = DESCRIPTOR.message_types_by_name[
KeyError: 'GetAssistantRoutinesRequest'

**Comment by markrgriffin** [comment]
Same issue here

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/google_home/api.py:11
Integration: Google Home (documentation, issues)
First occurred: 11:02:59 (1 occurrences)
Last logged: 11:02:59

Unexpected exception importing component custom_components.google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 17, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 11, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/client.py", line 24, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.10/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 24, in <module>
    _GETASSISTANTROUTINESREQUEST = DESCRIPTOR.message_types_by_name[
KeyError: 'GetAssistantRoutinesRequest'

**Comment by DerekF35** [comment]
I think this is the same issue that i reported 3 days prior.  Are you using google-wifi integration?

https://github.com/leikoilja/ha-google-home/issues/567

After upgrading HACS to 1.26.2 my issue appears to have gone away, but I can't point to why.  I've restarted a few times and it starts clean.

**Comment by DerekF35** [comment]
I spoke too soon.  After testing with 5 restarts and google_home loading fine for all 5, #6 google_home would not load with same error.

Question about whether you are all using google-wifi integration still stands.

**Comment by bmcclure** [comment]
I am using Google Wifi, it seems our issues may be the same then?

**Comment by DerekF35** [comment]
Yes, I think the scenario and error appear to match.  I didn't hit this particular integration issue with google-wifi until 1.9.13 on google_home.  Still unsure whether the issue is on google_home's side or google_wifi integration's side.
