### ISSUE TITLE
100 Character Limit Error

### ISSUE THREAD

**Issue by bredboye** [leikoilja/ha-google-home#705]
## Describe the bug

I'm told when entering credentials that password is limited to characters.  My password is exactly 100 characters. 
## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.17
```

## Logs

```text
2023-04-25 21:53:07.256 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-25 21:53:07.261 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-25 21:59:41.042 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140592341791264] Error handling message: Unknown error (unknown_error) Armando from 2601:6c1:c200:8da0:cc56:d2a8:7801:530f (Mozilla/5.0 (Linux; Android 13; SM-T870 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.136 Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-T870))
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 982, in async_install_repository
await self.download_content()
File "/config/custom_components/hacs/repositories/base.py", line 638, in download_content
raise HacsException("No content to download")
custom_components.hacs.exceptions.HacsException: No content to download
2023-04-25 22:05:59.384 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
2023-04-25 22:06:19.889 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
2023-04-25 22:06:50.350 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
2023-04-25 22:07:30.829 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
2023-04-25 22:08:21.333 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
2023-04-25 22:09:22.279 ERROR (stream_worker) [homeassistant.components.stream.stream.camera.nest_hub] Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiUA2vuxrxQYyigWZyBuQqNcgb3pQM6WCjka13TR5vwHDgnBe8GxEnEANrmTawjX9KGpAL0qINcfTyCinQRhQDEijI5TcSroKQZaVmWnAoYcl5Ui0E1vaWJAHYHRUj2-Ri5Zz4thEwnrXKbYD1FAPB-lQOp8rPe9KgYpofJ3Mc1WllojDIYaZV1p74o9IzGxkDCd7vKpKZl6Gg?auth=****
```

**Comment by leikoilja** [comment]
the error logs provided seem to have nothing with this integration. 
if the issue would be raised by `ha-google-home` or `glocaltokens` due to the password length you would see it in logs. Please check your logs (make sure to check README on how to enable the logs for this integration). If you see any relevant logs, please provide them here and we ll reopen
