### ISSUE TITLE
OSError: [Errno 98] Address in use

### ISSUE THREAD

**Issue by t-abraham** [leikoilja/ha-google-home#798]
## Describe the bug

I have used the full gmail address and app password along with the long master token. but then it says Needs Attention and in the log entries it says the following errors.

I am running HA in a docker in TrueNAS Scale and the network is privileged to Host network

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
v1.10.2
```

## Logs

```text
2023-11-18 21:22:11.184 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2023-11-18 21:22:11.184 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2023-11-18 21:22:11.184 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "", password to "", master_token to "a******************************************************************************************************************************************************************************************************************************" and android_id to 
2023-11-18 21:22:11.185 DEBUG (SyncWorker_3) [glocaltokens.client] There is no access_token stored, or it has expired, getting a new one...
2023-11-18 21:22:11.185 DEBUG (SyncWorker_3) [glocaltokens.client] Master token: a******************************************************************************************************************************************************************************************************************************
2023-11-18 21:22:11.185 DEBUG (SyncWorker_3) [glocaltokens.client] There is no stored android_id, generating a new one
2023-11-18 21:22:11.185 DEBUG (SyncWorker_3) [glocaltokens.client] Generating android id...
2023-11-18 21:22:11.185 DEBUG (SyncWorker_3) [glocaltokens.client] Generated android id: efe54888670b02d1
2023-11-18 21:22:11.350 DEBUG (SyncWorker_3) [glocaltokens.client] Access token: y*******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************, datetime 2023-11-18 21:22:11.350677
2023-11-18 21:22:11.353 DEBUG (MainThread) [custom_components.google_home] Coordinator update interval is: 0:03:00
2023-11-18 21:22:11.354 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Google Home (master_token) for google_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_home/__init__.py", line 53, in async_setup_entry
    zeroconf_instance = await zeroconf.async_get_instance(hass)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 142, in async_get_instance
    return cast(HaZeroconf, (await _async_get_instance(hass)).zeroconf)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 157, in _async_get_instance
    zeroconf = HaZeroconf(**zcargs)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_core.py", line 181, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 358, in create_sockets
    listen_socket = new_socket(ip_version=ip_version, apple_p2p=apple_p2p, bind_addr=('',))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zeroconf/_utils/net.py", line 248, in new_socket
    s.bind(bind_tup)
OSError: [Errno 98] Address in use
```

**Comment by KapJI** [comment]
Looks like there is another zeroconf instance already running on your system.

**Comment by t-abraham** [comment]
True. True as was using the scorer for mdns.
