### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by craigmcgowan** [leikoilja/ha-google-home#86]
Just installed this new component via HACS method and going through the configuration flow.

I did notice that Google local authentication token fetching shows up as the name, not Google Home as per your docs. But I know your only changing the name in the last day or so.

However, when I put my username and password in, I get an "unknown error occured".

This happens with my main password but also with an app password I created also. My HA log shows

```
021-03-11 15:56:31 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 150, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/glocaltokens/config_flow.py", line 46, in async_step_user
    CONF_ANDROID_ID: client.get_android_id(),
  File "/config/custom_components/glocaltokens/api.py", line 48, in get_android_id
    return self._client._get_android_id()
AttributeError: 'GLocalAuthenticationTokens' object has no attribute '_get_android_id'
```

If I use the wrong password, I do get a correct message "Username/Password is incorrect wrong. If your google account has 2FA enabled please generate app password (https://myaccount.google.com/apppasswords)"

Looking forward to being able to try this properly.

Kind regards

**Comment by leikoilja** [comment]
Hey, @craigmcgowan. From logs, it looks like you are using a very outdated version of the integration where we used to have `_get_android_id` method. 
This is most likely because when installing using HACS you have selected `0.0.1` version in the last dialog box. Since we haven't YET released public stable version, please use `master` in that dropdown. For that, simply remove integration now, remove HACS repo, add repo selecting `master` :)

**Comment by craigmcgowan** [comment]
Great, all sorted now. Sorry for my stupidity!

**Comment by leikoilja** [comment]
Oh no worries at all! 💥  Enjoy! 
But keep an eye on the release - that will allow automatic HACS updates, when while using `master` i don't think HACS does compare them to spot new updates
