### ISSUE TITLE
Can not log anymore after Google password change

### ISSUE THREAD

**Issue by Zilla31** [leikoilja/ha-google-home#920]
## Describe the bug

I used the Google Home HACS integration for couple of years with no issue. 2 weeks ago, I dediced to renew my Google password and I could not get anymore Google Home HACS integration working:
- No device/entities updated (it made sense as I modified my password)
- Decided to delete the integration and HACS component and re-install
- Despite use of 2FA and Google App password, I alwaus have the error "Username/Password is incorrect. If your google account has 2FA enabled please generate app password (https://myaccount.google.com/apppasswords). If authentication still fails refer to https://github.com/leikoilja/ha-google-home#troubleshooting"
- I did try to run the get_tokens.py but I do get BadAuthentication message with Master Token None
- I am user of LGThinQ so I did try also to delete this Integration as  have read some unexplained incompatibility in some post but without any success...

The Google Home Integration was quite useful in my Home Assistant environment acessing my alarm clock and I would love to get my access back :)

## Version of the integration

```text
V1.11.1
```

**Comment by Zilla31** [comment]
I am adding a log following a failed attempt to login:
Failed to get master token
Traceback (most recent call last):
  File "/config/custom_components/google_home/config_flow.py", line 138, in _get_master_token
    master_token = await client.async_get_master_token()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_home/api.py", line 81, in async_get_master_token
    raise InvalidMasterToken
custom_components.google_home.exceptions.InvalidMasterToken

Can i get any recommandation to proceed with the identification?
