### ISSUE TITLE
Unable to login with normal password or app password

### ISSUE THREAD

**Issue by Cypherous** [leikoilja/ha-google-home#930]
To help us to resolve this issue please include the following information:
- The GH integration just errors saying my username and password is invalid, its not i have triple checked, i even created an app password and that still can't login either
- Open integrations > click google_home > try to login
- I assume 1.12.1 as it was installed today and that is the most recent version
- Not installed, i am not after the master token i'm happy just giving it my login credentials
- No idea what logs you need nor how to get them

**Comment by halfspin-qc** [comment]
same issue here.... 
- I have 2 FA enabled
- I generated app password and still does not help
- Even tried just using my regular username and password but not useful
- In the steps I cannot get to the 'configure' option, the app can't be configured before authentication 
- Saw the logs but I am not able to debug the errors with my limited knowledge

**Comment by peterneuteboom** [comment]
same here: not able to log in with google username and app password

**Comment by mekeppler** [comment]
Same issue: not able to log in with google username and app password.

Tried 4 options:
- full email (xxx@gmail.com) with app-specific password
- full email (xxx@gmail.com) with my normal Google password
- username only (xxx) with app-specific password
- username only (xxx) with my normal Google password

See the same error in the logs every time:

```
2025-01-01 17:30:22.119 ERROR (SyncWorker_5) [glocaltokens.client] [!] Could not get master token.
2025-01-01 17:30:22.123 ERROR (MainThread) [custom_components.google_home] Failed to get master token
Traceback (most recent call last):
  File "/config/custom_components/google_home/config_flow.py", line 138, in _get_master_token
    master_token = await client.async_get_master_token()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_home/api.py", line 81, in async_get_master_token
    raise InvalidMasterToken
custom_components.google_home.exceptions.InvalidMasterToken
```

**Comment by giuseppebaldi** [comment]
Same here, tried every way possible. Seeing in logs [!] Could not get master token and Failed to get master token.

**Comment by Dengazzz** [comment]
same happened to me.

**Comment by mekeppler** [comment]
Any updates on what might be the issue?

**Comment by OliverBuschmann** [comment]
same issues did anyone solve this ?

**Comment by KapJI** [comment]
Duplicate of #890
